from oven/bun:1

WORKDIR /web

COPY . .
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/backend  ./apps/backend

RUN bun install
RUN bun run migrate
RUN bun run build

COPY . .

EXPOSE 3000

CMD ["bun","dev", "index.ts"]
