FROM oven/bun:1

WORKDIR /web

ARG DATABASE_URL

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock


COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend  ./apps/backend


RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build


EXPOSE 3000

CMD ["bun","dev", "index.ts"]
