name: Deploy the ws

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: mesusheel01/todo-app-ws:${{ github.sha }}
     ## deploying steps to vm
      - name: Deploy to vm
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_keys
          chmod 700 /home/runner/ssh_keys
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@34.45.114.30 -t  "docker stop user_backend && docker run --name user_backend -d -p 8080:8080 mesusheel01/my-todo-ws:${{github.sha}}"
